name: Tag

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current version
        id: version
        run: |
          CURRENT_VERSION=$(grep "version=" gradle.properties | cut -d= -f2)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Create Git Tag
        run: |
          TAG="v${{ steps.version.outputs.CURRENT_VERSION }}"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
